### PR TITLE
Add guidance and contextual information to CE frontend UI

### PR DESCRIPTION
**Pull request by rod-glover**
# Overview

Addresses #173

1. Replace existing navigation with the following multi-level nav:
    - Home/Data (original content)
       - Single dataset
       - Compare datasets
       - Extreme Precipitation
    - Help
       - FAQ
       - General
    - Science
    - About
      - etc.

2. Add information popovers explaining key elements, including the following:
    - Model, Emission, Variable selectors
    - Graph tabs

Revamping the navigation includes the following changes:

- Upgrade `react-router` to v4, "dynamic routing." This is a significantly different, more flexible, and (amazingly) at least as easy to use package. Worth reading about, and it works better than our old routing did.
- Use React Bootstrap `Nav` components throughout.
- Place top-level nav in app header; secondary nav appears in the page.
- Add a marmot. (Image by permission from [V.I. Marmot Recovery Foundation](https://marmots.org/)!)

Additionally, I have revised the layout to make it more consistent from data view to data view, to label things more clearly (with info popups for further explanation), and to indicate hierarchy and scope.

# To do

## Functionality

- [x] Add Datasets Summary panel to improve user's understanding of what dataset filtering does

## Layout

- [x] Fix layout of selectors and buttons in graphs
- [x] Fix layout of selectors and buttons in stats table
- [x] Fix layout of stats table proper
- [x] Add flow arrows to show relationship of datasets to data presentation elements

### FAQ

- [x] FAQ feedback request with contact info

### General

  - [x] What data is available
  - [x] Meanings of variables
  - [x] Map tools
  - [x] Map scales

### ~~Glossary~~

  - [ ] ~~Model, Emission Scenario, Variable~~
  - [ ] ~~Codes: do they belong in Glossary??~~
    - [ ] ~~Model codes~~
    - [ ] ~~RCP codes~~
    - [ ] ~~Variables, i.e., glossary item per variable, e.g., precip, climdex variables, ...~~
 - [ ] ~~Graph types (e.g., Long Term Average) - can probably dup from info popups~~

### Climate Explorer

- [x] Explain better
- [x] Author
- [x] Copyright?
- [x] Licence?
- [x] Terms (see PCIC Data Portals)

### Credits

- [x] Links to institutions providing data

### Contact

- [x] Feedback on tool
- [x] Scientific questions
- [x] PCIC

## Info popups

- [x] Map Settings
- [x] Map tools: Link in title popup to Help
- [x] Map scales: Link in title popup to Help
- [x] Stats table: Explain column sorting arrows

### Factor out common Col cases for top-level layout

- [x] refactoring
- [ ] establish good lg, md, sm vaues

## Misc

- [x] Fix text of Import Polygon diagog. Replace with "Accepts a zipped Shapefile or a GeoJSON file containing a single Feature (not a FeatureCollection)."
- [x] ~~Fix "layer" tooltips to read "polygon".~~ [Not possible.]
- [x] Choose either "colour blocks" or "raster" and use it consistently throughout. Suggest raster as it is shorter.

### CODE REVIEW

**Comment by rod-glover** [comment]
[Docker demo](http://docker-dev02.pcic.uvic.ca:30500/#/data/climo/ce_files)

**Comment by jameshiebert** [comment]
It has a marmot image... merge this immediately! :)

**Comment by corviday** [comment]
Wow, looks very good! Great job!

------------

I have an overarching philosophical question about help features: Do we want to slant them more toward the expected user, which I think is an engineer or policy maker, not a climate scientist?

For example, perhaps we'd change the emissions scenario selector tooltip from  "**Emission scenario used to drive the model run.**" to something that caters to an expected user who doesn't know what an emissions scenario is, like "**Emission scenarios represent a range of possible future projections for greenhouse gas emissions, which are input into climate models. Higher RCP values represent greater projected greenhouse gas emissions.**" 

We wouldn't want to write hundreds of words of popup - detailed explanations go in the FAQ - but I think we might like to add a "this is why you, an engineer, care about this thing" sentence to some of the existing ones?

-------

The stats table could use an info tag, I think, if for no other reason than [users find the function of the little table sorting arrows unclear](https://github.com/pacificclimate/climate-explorer-frontend/issues/166).

**Comment by jameshiebert** [comment]
I'd recommend that we engage our Scientific Information Specialist (Michael) for assistance with the language and what to say to target the right users.

**Comment by rod-glover** [comment]
[Demo](http://docker-dev02.pcic.uvic.ca:30500/#/data/climo/ce_files) updated.

Still quite a bit more help content to do, but the skeleton is there and the info popups and layout changes improve understandability quite a lot (I sincerely hope!).

**Comment by rod-glover** [comment]
[Demo](http://docker-dev02.pcic.uvic.ca:30500) updated.

**Comment by rod-glover** [comment]
[Demo](http://docker-dev02.pcic.uvic.ca:30500) updated.

This is getting close to beta. Comments/feedback welcome. 

What do you think of the "flow arrows" that show (at least in my mind) how datasets are selected and displayed?

**Comment by rod-glover** [comment]
This PR replaced by the following:
#198 
#200 
#205 
#208 
#210

**Pull request closed without merging**
