### PR TITLE
Improve docker instructions in README

### LINKED ISSUE #287: Improve docker instructions in README

### PR DESCRIPTION
**Pull request by rod-glover**
Resolve #287

### CODE REVIEW

**Comment by corviday** [comment]
The content seems accurate and clear. Do these site-specific details make more sense in Confluence than in the public README, though?

**Comment by rod-glover** [comment]
That's a good question. I wanted to avoid having to go to multiple places to get a complete description of how to build and deploy manually. I still want that; I suppose we could migrate this to a specific Confluence page that is linked in the README. Question: Is it worth the extra effort and complication?

**Comment by corviday** [comment]
>  _Is it worth the extra effort and complication?_

I lean toward "no". There's already some site-specific information in the README, and I doubt anyone not associated with PCIC is ever going to run this, so where the information goes is a matter of aesthetics, more than utility.

**Comment by rod-glover** [comment]
Good, I lean that way too. And it's not as if we can't change our minds easily.

**Pull request merged**
